name: Java CI with Maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-with-maven-cache-github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Restore cache
      uses: skjolber/maven-cache-github-action@v3.1.2
      with:
        step: restore
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action@v3.1.2
      with:
        step: save
  build-with-github-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
        cache: maven
    - name: Echo settings
      run: cat ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  beta-wrapper-not-invoked:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Restore cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: restore
        cache-key-prefix: wrapper-not-invoked
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: save
  beta-wrapper-invoked:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Restore cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: restore
        cache-key-prefix: wrapper-invoked
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: save
  beta-wrapper-disabled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Restore cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: restore
        cache-key-prefix: wrapper-disabled
        wrapper: false
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: save

