name: Java CI with Maven

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-with-maven-cache-github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
    - name: Restore cache
      uses: skjolber/maven-cache-github-action@v3.0
      with:
        step: restore
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action@v3.0
      with:
        step: save
  build-with-github-cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica
        cache: maven
    - name: Echo settings
      run: cat ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  build-with-maven-cache-github-action-beta:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: liberica      
    - name: Restore cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: restore
        cache-key-prefix: maven-cache-github-action-beta
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Save cache
      uses: skjolber/maven-cache-github-action-beta@v1
      with:
        step: save

